### ISSUE TITLE
TCGA - access to s3 bucket with controlled access.

### ISSUE THREAD

**Issue by tweep** [awslabs/open-data-registry-browser#196]
Hello there, 

we've got a question regarding the access of access-controlled TCGA data. Here's the story: 

- We've got an active dbGaP approval to access TCGA data
- we saw that this data is available on s3 as outlined [here](https://registry.opendata.aws/tcga/) .

This got us excited, as this would allow us to leverage that data together with other AWS infrastructure in a simple way, similar to how we access the non-access-controlled s3 data. To my understanding, the sharing of access restricted data can be done in a similar way as described [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-walkthroughs-managing-access-example1.html) 

I've contacted AWS and the suggested work-around is to go trough [this process](https://gdc.cancer.gov/access-data/data-access-processes-and-tools) , download the data via pre-signed urls, validate / check data and then upload it back into (our own) s3 account to finally process it, and sync data whenever new data sets become available. This seems unnecessarily complex.

So the question is : *How can we leverage this data *directly* (after authentication) without downloading and re-uploading hit ?*

If this is not possible right now, is there a plan to move this forward and manage access via s3 grants ? 

Thanks
   Jan

**Comment by chueatwork** [comment]
Hi Jan,

Thanks for reaching out. I think we have been discussing this over email; last I spoke with Ariella we have a meeting scheduled to discuss potential solutions. I will also provide this feedback to the data provider.

Thanks!
Erin
